-- ============================================================================
-- outlook — la proyección de reclutamiento (etapa OL20)
-- ============================================================================
--
-- NO EJECUTAR desde el repo. Lo aplica quien administra la base.
--
-- Tres tablas para proyectar a la gente que TODAVÍA NO ESTÁ EN EL ROSTER:
-- cuánto se espera que produzca y desde cuándo.
--
--   recruitment_projection   la proyección de una persona
--   recruitment_ramp         la rampa de adaptación, global
--   recruitment_link         la identidad, cuando se sabe cuál es
--
-- Append-only, sin UPDATE ni DELETE, con revisión entera, autor y fecha --
-- mismo patrón que `growth_rule` y `strategy_benchmark`, y por el mismo motivo:
-- un presupuesto que se corrige tiene que dejar ver qué decía antes y quién lo
-- cambió.
--
-- ---------------------------------------------------------------------------
-- ⚠ NADA DE ESTO TOCA `org.dim_employee` NI EL ROSTER
-- ---------------------------------------------------------------------------
--
-- Una proyección no es una persona contratada. El día que entre de verdad va a
-- aparecer en `org.roster_current` por su cuenta, y a partir de ahí la proyecta
-- el motor de siempre. Escribir en el roster desde acá crearía una persona que
-- RRHH nunca dio de alta.
--
-- Ese es también el riesgo principal de la etapa --el doble conteo-- y se
-- resuelve más abajo, en `recruitment_link` y en la regla de vencimiento.

-- ── 1. La proyección de una persona ─────────────────────────────────────────
--
-- ⚠ UNA FILA POR REVISIÓN, no una fila por persona. La vigente es la de
-- `revision` más alta para la misma `identity`. Corregir una fecha no borra la
-- anterior.
--
-- `identity` es la clave estable de la persona proyectada:
--   · de la fuente:  'future:' || id_fuente
--   · creada a mano:  'manual:' || un uuid que asigna la app
-- No se usa el nombre. Los nombres difieren entre fuentes y hay dos `Jose
-- Flores` distintos en los mismos 15 registros de hoy.

create table if not exists outlook.recruitment_projection (
  recruitment_projection_key bigint generated by default as identity primary key,
  identity        text        not null,
  revision        integer     not null,
  source          text        not null check (source in ('future_loan_officer', 'manual')),
  person_name     text        not null,
  role            text        not null check (role in ('loan_officer', 'nppm')),
  -- ⚠ EDITABLE, y por eso vive acá y no se lee de la fuente. `branch_code =
  -- 'Recruitment'` es un marcador de "todavía no se sabe", no un branch real:
  -- son 5 personas hoy. Cuando se sepa a dónde va alguien, se corrige sin
  -- esperar a que la fuente lo traiga.
  branch_code     text        not null,
  -- Cuándo entra. Precargada de `fecha_inicio` cuando existe -- sólo la traen
  -- los 2 de `hr_pipeline`; los 13 de Salesforce no tienen ninguna.
  --
  -- ⚠ NO ES `close_date`. Esa es cuándo se cerró el reclutamiento, no cuándo
  -- empieza a trabajar. Usarla adelantaría la producción de todos.
  start_date      date,
  -- Desde qué mes cuenta para el presupuesto, 'YYYY-MM'. Puede ser posterior a
  -- `start_date`: entrar y producir no son el mismo mes.
  producing_from  text        not null check (producing_from ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  -- ⚠ NULL Y 0 NO SIGNIFICAN LO MISMO, y por eso admite NULL sin default.
  -- NULL = nadie fijó cuánto se espera que produzca. 0 = alguien decidió que
  -- no produce. Es la misma distinción que el resto del módulo mantiene, y acá
  -- importa más que en otros lados: hoy `outlook.strategy_benchmark` tiene DOS
  -- filas en toda la tabla, las dos de B2B, así que no hay ni un benchmark de
  -- Recruitment del cual precargar. Los 15 arrancan en NULL y visibles.
  monthly_benchmark numeric   check (monthly_benchmark is null or monthly_benchmark >= 0),
  -- El único identificador que une esta tabla con `org.dim_employee.nmls` sin
  -- adivinar. 6 de los 15 lo traen; 44 de los 127 empleados lo tienen.
  nmls            text,
  set_by          text        not null,
  note            text,
  created_at      timestamptz not null default now(),
  unique (identity, revision)
);

create index if not exists recruitment_projection_identity_idx
  on outlook.recruitment_projection (identity, revision desc);

-- ── 2. La rampa de adaptación ───────────────────────────────────────────────
--
-- Decisión del negocio: un recluta nuevo no produce su benchmark completo desde
-- el primer mes.
--
--   mes 1 desde `producing_from`  ->  25%
--   mes 2                          ->  50%
--   mes 3 en adelante              ->  100%
--
-- ⚠ GLOBAL, NO POR PERSONA. Es un tiempo de adaptación al puesto, no una
-- característica de nadie. Si algún día hace falta por persona, se agrega una
-- columna `identity` nullable y la global queda como el caso `null` -- mismo
-- patrón que `growth_rule`, que ya convive entre persona y branch.

create table if not exists outlook.recruitment_ramp (
  recruitment_ramp_key bigint generated by default as identity primary key,
  revision        integer     not null unique,
  month_1_pct     numeric     not null check (month_1_pct between 0 and 1),
  month_2_pct     numeric     not null check (month_2_pct between 0 and 1),
  month_3_plus_pct numeric    not null check (month_3_plus_pct between 0 and 1),
  set_by          text        not null,
  note            text,
  created_at      timestamptz not null default now()
);

-- ── 3. La identidad, cuando se sabe ─────────────────────────────────────────
--
-- ============================================================================
-- ⚠ ESTO ES LO QUE EVITA EL DOBLE CONTEO. Leer antes de tocar nada.
-- ============================================================================
--
-- El problema: una persona proyectada que después entra al roster suma por los
-- dos lados. `remainingMonths` de Outlook arranca en el mes SIGUIENTE al
-- actual, así que no hay solapamiento con el pasado -- pero en cuanto la
-- persona está en el roster, las dos proyecciones cubren los mismos meses
-- futuros.
--
-- ⚠ UN CRUCE POR NOMBRE NO ALCANZA, y hay prueba dentro de los propios datos:
-- `Jose Flores` (hr_pipeline, branch 728, entra el 2026-09-01, sin NMLS) y
-- `Jose Flores Tortoza` (salesforce, tentative, NMLS 2342452). Un cruce por
-- nombre o los une siendo distintos, o los separa siendo el mismo, y desde acá
-- no hay forma de saber cuál de las dos cosas es.
--
-- Tres capas, en orden de certeza:
--
--   1. NMLS exacto, automático. Donde los dos lados lo tienen, el match ES
--      identidad: es un registro nacional único por licenciado, no una
--      heurística. No necesita fila en esta tabla.
--   2. El vínculo explícito, esta tabla. Alguien confirma una vez y queda. Es
--      el único mecanismo cierto para los 9 que no traen NMLS.
--   3. `org.employee_alias` sólo para PROPONER candidatos en el aviso de la
--      pantalla. Nunca para decidir.
--
-- ⚠ Y LA REGLA QUE SE CURA SOLA, que no vive acá sino en el cálculo: una
-- proyección cuyo `producing_from` YA PASÓ y que sigue sin vincular DEJA DE
-- CONTAR, y aparece pidiendo decisión. Pasada su fecha, o la persona ya está en
-- el roster --y contarla duplica-- o no entró --y contarla inventa--. En los dos
-- casos lo correcto es que no sume.
--
-- El modo de falla que eso elige es deliberado: presupuesto CORTO Y VISIBLE
-- antes que inflado y silencioso. Ya pasó al revés en OL1b, con el total en 105
-- cuando eran 44, y un número inflado no lo detecta nadie porque se ve
-- plausible.
--
-- Desvincular es una fila NUEVA con `employee_key` en NULL, no un DELETE: la
-- vigente es la más reciente por `identity`.

create table if not exists outlook.recruitment_link (
  recruitment_link_key bigint generated by default as identity primary key,
  identity        text        not null,
  -- NULL = se desvinculó. Ver la nota de arriba.
  employee_key    bigint      references org.dim_employee (employee_key),
  linked_by       text        not null,
  note            text,
  created_at      timestamptz not null default now()
);

create index if not exists recruitment_link_identity_idx
  on outlook.recruitment_link (identity, created_at desc);

-- ── Permisos ────────────────────────────────────────────────────────────────
--
-- `select, insert` y nada más, igual que el resto del esquema: sin UPDATE ni
-- DELETE no hay forma de perder una revisión anterior, ni por error ni a
-- propósito.

grant select, insert on outlook.recruitment_projection to authenticated;
grant select, insert on outlook.recruitment_ramp to authenticated;
grant select, insert on outlook.recruitment_link to authenticated;
grant usage on all sequences in schema outlook to authenticated;

alter table outlook.recruitment_projection enable row level security;
alter table outlook.recruitment_ramp enable row level security;
alter table outlook.recruitment_link enable row level security;

create policy recruitment_projection_select on outlook.recruitment_projection
  for select to authenticated using (outlook.has_access());
create policy recruitment_projection_insert on outlook.recruitment_projection
  for insert to authenticated with check (outlook.has_access());

create policy recruitment_ramp_select on outlook.recruitment_ramp
  for select to authenticated using (outlook.has_access());
create policy recruitment_ramp_insert on outlook.recruitment_ramp
  for insert to authenticated with check (outlook.has_access());

create policy recruitment_link_select on outlook.recruitment_link
  for select to authenticated using (outlook.has_access());
create policy recruitment_link_insert on outlook.recruitment_link
  for insert to authenticated with check (outlook.has_access());

-- ── La rampa por defecto ────────────────────────────────────────────────────
--
-- Revisión 1 con los porcentajes que fijó el negocio. Sin esta fila el cálculo
-- cae a los mismos valores por código (ver `DEFAULT_RAMP` en
-- `lib/outlook/recruitment.ts`), así que la etapa funciona antes de aplicar
-- este SQL -- pero entonces la rampa no es editable, que es la mitad del
-- pedido.

insert into outlook.recruitment_ramp
  (revision, month_1_pct, month_2_pct, month_3_plus_pct, set_by, note)
values
  (1, 0.25, 0.50, 1.00, 'ol20-seed', 'Rampa inicial fijada por el negocio: 25/50/100.')
on conflict (revision) do nothing;

-- ── Cómo se consulta la vigente ─────────────────────────────────────────────
--
--   -- la proyección vigente de cada persona
--   select distinct on (identity) *
--   from outlook.recruitment_projection
--   order by identity, revision desc;
--
--   -- el vínculo vigente, incluidos los desvinculados
--   select distinct on (identity) identity, employee_key
--   from outlook.recruitment_link
--   order by identity, created_at desc;
